#TB-6 STYLE: 도메인 기반 아키텍쳐 예시 작성
Team-Butler/go-calendar-practice pull request #3
Opened 2022-04-19 14:25 UTC by Marades

Domain기반 아키텍처를 예시로 간단하게 구현해봤습니다
Go와 맞지 않거나 부족한 부분에 대해서 리뷰해주시면 감사하겠습니다!

2022-04-20 05:13 UTC, handal95 commented
#1 [#TB-6 Gin Framework Prototype] PR에 대해서 리뷰 진행되지 않는다면, 닫아둘까요?

2022-04-20 05:43 UTC, handal95 requested changes
내부 로직은 안보고 Go 표준 방식이랑 차이가 있는 부분들에 리뷰 남겼습니다~ 
*Hello, World! 오타는 Go와 관계없지만 못 참음

혹시 괜찮다면, 아키텍쳐 예시 `README.md` / `docs/architecture.md`에 각 디렉토리에 대한 간단한 설명 부탁드려도 될까요? 눈으로 보는거랑 전달되는 의도가 다를 수도 있으니까!

2022-04-20 05:43 UTC, handal95 commented on pkg/modules/example/example.service.go
> +	return http.StatusOK, "Hello, Wolrd"
```suggestion
	return http.StatusOK, "Hello, World!"
```

🤣

2022-04-20 05:43 UTC, handal95 commented on cmd/entry.go
> +	r := gin.Default()
```suggestion
	router := gin.Default()
```
약어 사용은 최대한 풀어주세요

Go에서는 같은 변수명은 재선언 등이 아예 안되서, 짧은 범위에서도 줄여쓰는 것보다 명시적으로 구분해주는 편이 좋습니다

보통 한글자 축약어는 데코레이터 패턴에서 (아주 권장되지는 않지만)한정적으로 사용하곤 합니다.

2022-04-20 05:43 UTC, handal95 commented on pkg/loaders/api.go
> +func LoadApis(r *gin.Engine) {
```suggestion
func LoadAPIs(r *gin.Engine) {
```
Go에서 약어를 사용하는 경우에는 약어 문자 전체를 UPPERCASE 혹은 lowercase 로 적어주세요. 일반적으로 Api, Url, Http 같은 방식은 Go에서 사용되지 않습니다

> Words in names that are initialisms or acronyms (e.g. "URL" or "NATO") have a consistent case. For example, "URL" should appear as "URL" or "url" (as in "urlPony", or "URLPony"), never as "Url". As an example: ServeHTTP not ServeHttp. For identifiers with multiple initialized "words", use for example "xmlHTTPRequest" or "XMLHTTPRequest".

[Reference](https://github.com/golang/go/wiki/CodeReviewComments#initialisms)

2022-04-20 05:43 UTC, handal95 commented on pkg/modules/example/example.controller.go
> +}
호호 빨간색은 넘모 신경쓰여용
언젠가 Git Action으로 걸어둬야하는데 일단 그렇습니다

Go Lint Repo는 업데이트가 되지 않아 중단되엇으니 golangci-lint 이용하면 좋을 것 같아요
[golangci-lint Github](https://github.com/golangci/golangci-lint)

2022-04-20 05:45 UTC, handal95 commented on pkg/modules/example/example.controller.go
> +}
앗 표시가 안되있는데 Linting 안되서 Review상 빨간색 금지 마킹 떠있어여

2022-04-20 05:52 UTC, Marades commented on cmd/entry.go
> +	r := gin.Default()
아하! 저도 약어는 최대한 풀어서 쓰는 걸 지향하는데 gin 라이브러리의 예제 코드 스타일이 router를 r로 표현하는 거 같아 일단 따랐었습니다..! 그게 권장사항이 아니였군요
반영하도록 하겠습니다

2022-04-20 05:53 UTC, Marades commented on pkg/loaders/api.go
> +func LoadApis(r *gin.Engine) {
알겠습니다! 레퍼런스까지 남겨주셔서 감사합니다

2022-04-20 06:11 UTC, handal95 commented on cmd/entry.go
> +	r := gin.Default()
[공식 Gin Repository](https://github.com/gin-gonic/gin) 에서 API Example을 확인해보면 router로 적는게 표준이긴 합니다!

아마 QuickStart 예제를 바탕으로 초기 Framework 구축하는 부분에서 다들 r로 적는거같아요

2022-04-21 15:19 UTC, handal95 commented
작업 분배 일정상, 상호합의된 부분에 대해서 수정을 진행했습니다.

추가로 수정한 부분은 다음과 같습니다.
1. :8080 PORT를 사용중일 때, 서버가 실행되지 않음에도 server start 가 출력되는 오류를 수정했습니다.
2. `modules/`내에서 `example/`그룹 외에도 root(`/`)를 기반으로 하는 base 그룹을 하나 더 추가했습니다.
    - 내부 로직은 본 PR 범위를 벗어나는 것 같아서 일단 example을 복사했습니다.
3. `cmd/entry.go` 파일명을 `cmd/main.go`로 수정해두었습니다. 
4. 린팅을 적용했습니다.
    - 위에서 추천했던 [golangci-lint](https://github.com/golangci/golangci-lint/issues/2649)가 go 1.18에서 호환성이슈가 있어서 해당 linter를 적용하는건 보류해야될 것 같습니다.
5. README.md 에 파일트리를 추가해뒀습니다. 아키텍쳐 관련해서 논리개념상 경로별로 어떤 파일들이 정리되어야 하는지, @Marades 의도를 적어주시면 좋을 것 같습니다
6. 일부 오타 혹은 명명을 조금 수정했습니다

2022-04-21 15:20 UTC, handal95 commented
아니 이렇게 적고보니까 뭐 많이 건든 것처럼 보이는데, 사실 크게 건들지 않았습니다 호호

보고 아니다 싶은 부분은 롤백해주세용

2022-04-22 14:43 UTC, Marades reviewed
LGTM입니당

2022-04-22 17:04 UTC, handal95 approved these changes

2022-04-22 17:05 UTC, merged